[package]
name = "urspace-bootstrap"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
iroh-base = { workspace = true, features = ["key"] }
tokio = { workspace = true, features = ["fs", "macros", "net", "rt-multi-thread"] }

[dev-dependencies]
tempfile = "3"
