[package]
name = "medousa-site-browser"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
getrandom.workspace = true
iroh.workspace = true
iroh-tickets.workspace = true
medousa-site-protocol = { path = "../medousa-site-protocol" }
n0-future.workspace = true
serde.workspace = true
serde-wasm-bindgen = "0.6"
tokio = { workspace = true, features = ["io-util", "sync"] }
url.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
zeroize.workspace = true
