[package]
name = "medousa-site-protocol"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
base64.workspace = true
iroh-base.workspace = true
iroh-tickets.workspace = true
postcard.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["io-util"] }
url.workspace = true
uuid.workspace = true
